### ISSUE TITLE
fatal: unable to update url base from redirection

### ISSUE THREAD

**Issue by solsson** [adohkan/git-remote-https-iap#5]
## Expected Behavior

Consistently work like the 10-50% of attempts that don't get the redirect.

## Actual Behavior

With no changes in how we use `git-remote-https+iap`, since late last week most of our git fetch and push attemtps result in 

```
% GIT_IAP_VERBOSE=1 GIT_TRACE=true git fetch
16:03:50.102505 exec-cmd.c:139          trace: resolved executable path from Darwin stack: /Library/Developer/CommandLineTools/usr/bin/git
16:03:50.103081 exec-cmd.c:238          trace: resolved executable dir: /Library/Developer/CommandLineTools/usr/bin
16:03:50.103696 git.c:455               trace: built-in: git fetch
16:03:50.106250 run-command.c:667       trace: run_command: GIT_DIR=.git git remote-https+iap origin https+iap://git.example.net/example/repo
16:03:50.109391 exec-cmd.c:139          trace: resolved executable path from Darwin stack: /Library/Developer/CommandLineTools/usr/libexec/git-core/git
16:03:50.109809 exec-cmd.c:238          trace: resolved executable dir: /Library/Developer/CommandLineTools/usr/libexec/git-core
16:03:50.110135 git.c:743               trace: exec: git-remote-https+iap origin https+iap://git.example.net/example/repo
16:03:50.110147 run-command.c:667       trace: run_command: git-remote-https+iap origin https+iap://git.example.net/example/repo
{"level":"debug","time":"2022-01-17T16:03:50+01:00","message":"/Users/me/example/ystack/bin/git-remote-https+iap origin https+iap://git.example.net/example/repo"}
{"level":"debug","time":"2022-01-17T16:03:50+01:00","message":"Manage IAP auth for https://git.example.net"}
{"level":"debug","time":"2022-01-17T16:03:50+01:00","message":"IAP Cookie still valid until 2022-01-17 16:51:15 +0100 CET"}
{"level":"debug","time":"2022-01-17T16:03:50+01:00","message":"passThruRemoteHTTPSHelper exec: [git remote-https origin https://git.example.net/example/repo]"}
16:03:50.122336 exec-cmd.c:139          trace: resolved executable path from Darwin stack: /Library/Developer/CommandLineTools/usr/libexec/git-core/git
16:03:50.122667 exec-cmd.c:238          trace: resolved executable dir: /Library/Developer/CommandLineTools/usr/libexec/git-core
16:03:50.122985 git.c:743               trace: exec: git-remote-https origin https://git.example.net/example/repo
16:03:50.122998 run-command.c:667       trace: run_command: git-remote-https origin https://git.example.net/example/repo
16:03:50.125879 exec-cmd.c:139          trace: resolved executable path from Darwin stack: /Library/Developer/CommandLineTools/usr/libexec/git-core/git-remote-https
16:03:50.126181 exec-cmd.c:238          trace: resolved executable dir: /Library/Developer/CommandLineTools/usr/libexec/git-core
fatal: unable to update url base from redirection:
  asked for: https://git.example.net/example/repo/info/refs?service=git-upload-pack
   redirect: https://accounts.google.com/ServiceLogin?continue=https%3A%2F%2Faccounts.google.com%2Fsignin%2Foauth%2Flegacy%2Fconsent%3Fauthuser%3Dunknown%26part%3DAJ
```

The behavior is the same if I delete the cookie file.

## Steps to Reproduce the Problem

  1. Configure according to README
  1. Git fetch or push

## Specifications

  - Version: 0.1.1
  - Git version: `2.32.0 (Apple Git-132)`
  - Operating System: OSX Monterey

**Comment by ryanm101** [comment]
Yes, we've been encountering this issue since friday. We suspect it was an IAP change but at this point not sure. 

We've also seen the same behaviour when using our `cookie` and curl. All of our internal comms to GIT that don't go via IAP work fine. 


Glad to see this isn't localised to us though.

**Comment by ryanm101** [comment]
@solsson we are raising a ticket with GCP about it, it would be worth (if you have support) you doing the same so they get multiple notices of the issue.

Note all our web browser iap requests work fine.

**Comment by henricook** [comment]
A little recreation case for this that removes `git-remote-https-iap` and git from the possibility of being the cause.

If your cookieFile set by the git-remote-https-iap is at `~/.config/gcp-iap/my-site-com.cookie`

You could run `curl -vs -b ~/.config/gcp-iap/my-site.cookie https://my-site.com` - what you'll see using simple curl is that IAP responses are sporadically "you are allowed through (200)" and "you are not allowed through I need to redirect you (303)"

**Comment by solsson** [comment]
@henricook You're right, if I repeat the `curl` command above I get roughly the same error rate as with git fetch, or maybe a bit lower but that could be randomness.

I suspected this was the case because we're using these tokens (through the `print` command from #2) in direct curl calls without cookie, and they consistently work.

**Comment by solsson** [comment]
So the issue isn't with git, it's that `curl -b` fails at random while `curl -H "Authorization: Bearer ..."` doesn't? Do we know anything else that could be of value in the GCP issues? Is the cookie format `my.example.net	x	x	x	1642608962	GCP_IAAP_AUTH_TOKEN	eyJhbG....` relevant in any way?

Have you looked for ways to populate the Bearer token in git calls instead of using a cookie?

**Comment by henricook** [comment]
That's the sum of where we've got to at the moment as well, and what we're now waiting on GCP support to assist us with.

We performed a successful test with Bearer Authorization headers but we find they usually conflict with whatever application we're accessing that wants to set its own Bearer Authorization header - which means it's not an effective solution.

I would be happy to share some thoughts in implementing that on a fork if you think it'll suit your use case.

**Comment by henricook** [comment]
A tip from @ryanm101 - if we were going down that route we might use `Proxy-Authorization` - https://cloud.google.com/iap/docs/authentication-howto#authenticating_from_proxy-authorization_header

**Comment by ryanm101** [comment]
@solsson We think we have a fix/workaround with the `Proxy-Authorization` that seems to work we'll update the code here once we've tested it.

**Comment by ryanm101** [comment]
In short we just tweak the cli args at runtime to pass `extraheader` to the git command containing the ProxyAuth + Token

**Comment by ryanm101** [comment]
https://stackoverflow.com/a/70820466/2432240
